-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 44e1753f98b0da305332abe26856c3e621c5c439
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    sha: 017e2f64306853ec7f000db52b8280da27eb3b96
    hooks:
    -   id: reorder-python-imports
        language_version: python3.5
